### ISSUE TITLE
Updating Go version in go.mod breaks backwards compatibility

### ISSUE THREAD

**Issue by dgreene-r7** [goadesign/clue#344]
Per the docs, the `go` directive in `go.mod` defines the [minimum version required to use the module](https://go.dev/ref/mod#go-mod-file-go). Updating the go version, especially in minor releases represents breaking changes and generally violates semver. Is there any particular reason that This repo now targets 1.21? If there's no issue with backwards compatibility in terms of code features, can this be rolled back to an earlier version?

**Comment by raphael** [comment]
You are correct that the go.mod file should target the lowest compatible Go version. In this case we wanted to start using workspaces to manage the sub modules of this repo. Is upgrading to Go 1.21 causing issues?

**Comment by dgreene-r7** [comment]
It's less about upgrading to Go 1.21 and more that there's breaking changes in a minor release. We usually lag 1 minor version behind Go's tip as a stability concern. I think this is probably more of an argument with Go introducing changes in a minor version that has compatibility implications even if they were unintended. I'll close this issue as it's not productive. Thanks for the info!
