### ISSUE TITLE
Logger support for WARN level

### ISSUE THREAD

**Issue by jace-ys** [goadesign/clue#467]
Just out of interest, why does the clue log package not provide support for logging at `WARN` level?

Seems like most packages like https://pkg.go.dev/log/slog have support for the main 4 log levels: `DEBUG`, `INFO`, `WARN`, `ERROR`.

Would be great to include support for `WARN` in clue log! I'm happy to open a PR if I get the greenlight.

**Comment by raphael** [comment]
Sorry for the late reply! Yes that makes sense - would be great to get a PR that would add support for the WARN level.
