### ISSUE TITLE
Add a function to inject a logger into a context

### ISSUE THREAD

**Issue by ernesto-jimenez** [goadesign/clue#68]
Right now, `clue/log` is the only package that can define a middleware like `log.HTTP`, since `ctxLogger ` is unexported.

It's feasible other people might have to develop their own middlewares, so it would be good to have something like:
```golang
log.WithContext(requestCtx, loggerCtx)

// Maybe include this too:
log.MustContainLogger(ctx)

// within clue
func MustContainLogger(logCtx context.Context) {
  	l := logCtx.Value(ctxLogger)
	if l == nil {
		panic("provided context without log.Context()")
	}
}
```

It would allow things like:
```go
func WorkerLog(logCtx context.Context) func(worker.Handler) worker.Handler {
	...
}
```

**Comment by raphael** [comment]
Makes sense! Left a few comments in the commit, we can merge once these are addressed.
