### ISSUE TITLE
Inconsistencies in logging keys

### ISSUE THREAD

**Issue by ernesto-jimenez** [goadesign/clue#71]
Right now the `goa` logging HTTP middleware and `log.HTTP` use different keys to log request IDs: `id` and `requestID`.

It would be good to converge both.

**Comment by raphael** [comment]
Makes sense, would be probably hard to change how Goa does it at this point without breaking many users but `requestID` seems to be what the industry is settling on...

**Comment by ernesto-jimenez** [comment]
PR #90 should improve this.

**Comment by ernesto-jimenez** [comment]
@raphael should we close this in favour of https://github.com/goadesign/goa/issues/3057 ?

**Comment by raphael** [comment]
Yeah I like that idea.
