### ISSUE TITLE
With GET endpoint with parameter, metrics are generated for each value of the parameter

### ISSUE THREAD

**Issue by williammoran** [goadesign/clue#86]
With an http endpoint like "/v1/item/{itemid}" I'm having a problem where clue is generating a new set of metrics every time a new {itemid} is requested, which is going to result in millions of metrics for this GET endpoint alone.

I would expect clue to generate a single metric for "/v1/item" and collapse all values of {itemid} into this one metric.

**Comment by raphael** [comment]
Thank you for the report, this is a bug, the route used to label the metrics should be the 'design' route (i.e. using `/{itemid}` and not the actual route.

**Comment by raphael** [comment]
There is now an option that one can set when creating a metrics context that allows providing a function that can give the value used for the HTTP path label. This function accepts a request and returns the value for the label. When using Goa the function can be implemented with:
```go
func routeResolver(req *http.Request) string {
    return httptreemux.ContextRoute(req.Context())
}
```
With this example the metrics context would then be created using e.g.:
```go
ctx = metrics.Context(ctx, genfront.ServiceName, metrics.WithRouteResolver(routeResolver)
```

**Comment by raphael** [comment]
Added to the `weather` example as well: https://github.com/goadesign/clue/blob/main/example/weather/services/front/cmd/front/main.go#L73-L77
